services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3030:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - apis

  apis:
    build:
      context: ./apis
    ports:
      - "5050:8000"
    volumes:
      - ./apis:/app
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=woyafal
    depends_on:
      - mysql

  mysql:
    #image: mysql:latest
    image: mysql:8.4
    ports:
      - "6060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: woyafal
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysql-data:
